# Generated by Django 6.0.2 on 2026-02-23 03:18

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('emoji', models.CharField(default='📢', max_length=10)),
                ('custom_url', models.CharField(blank=True, help_text='Custom URL e.g. /gallery/ (used if no post linked)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('link_post', models.ForeignKey(blank=True, help_text='Link to a notice post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
