# Generated by Django 6.0.2 on 2026-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_document_marqueeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_open', models.BooleanField(default=True)),
                ('admission_closed_message', models.TextField(default='Admissions for this session are now closed. Please check back later for the next session.')),
                ('admission_open_date', models.DateField(blank=True, help_text='Next admission opening date (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='lab',
            name='lab_type',
            field=models.CharField(choices=[('science', 'Science Lab'), ('physics', 'Physics Lab'), ('chemistry', 'Chemistry Lab'), ('biology', 'Biology Lab'), ('computer', 'Computer Lab'), ('library', 'Library'), ('other', 'Other')], max_length=20),
        ),
    ]
