# Generated by Django 6.0.2 on 2026-02-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_admissionapplication_applying_for_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(help_text='e.g. 2026-27', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Toggle admission open/close')),
                ('forms_open_date', models.DateField(blank=True, null=True)),
                ('forms_close_date', models.DateField(blank=True, null=True)),
                ('admission_test_date', models.CharField(blank=True, help_text='e.g. March 23-24, 2026', max_length=100)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=3000, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('closed_message', models.TextField(default='Admissions for this session are now closed. Please check back later.')),
                ('next_open_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Admission Session',
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.admissionsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(help_text='e.g. Class XI', max_length=20)),
                ('combination', models.CharField(help_text='e.g. PCMB + Mizo', max_length=200)),
                ('combination_full', models.TextField(help_text='e.g. Physics, Chemistry, Mathematics, Biology, English, Mizo')),
                ('value', models.CharField(help_text='Form value e.g. XI-PCMB+Mizo', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='main.admissionsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
